### ISSUE TITLE
Nothing in /sdcard but MTP works on Windows 10

### ISSUE THREAD

**Issue by imknown** [CaptainThrowback/android_device_htc_hima#1]
I cannot see the files in the TWRP, neither in `20190918-02-hima_SAR` nor `20200116-02-hima_SAR` .
But I can see the files on Windows 10 File Manager via MTP. After I wipe the `Internal Storage` partition, and copy something to the `/sdcard`, I can see them again. Then I reboot into TWRP, the issue happens again.

P.S.: `20190918-02-hima_SAR` works before. After I installed the `aicp_hima_q-15.0-UNOFFICIAL-20200115.zip`, the TWRP does not work.

[dmesg.log](https://github.com/CaptainThrowback/android_device_htc_hima/files/4075154/dmesg.log)
[recovery.log](https://github.com/CaptainThrowback/android_device_htc_hima/files/4075155/recovery.log)

**Comment by imknown** [comment]
It seems like that the TWRP works after I reinstalled the LOS 17.1 and reboot into the TWRP again, though the log the TWRP shows the error `E:Unable to decrypt FBE device` .

**Comment by CaptainThrowback** [comment]
You can ignore that FBE error. That requires an upstream fix. I'm still uncertain as to what exactly you're reporting as an issue, though.

**Comment by imknown** [comment]
@CaptainThrowback The issue disappears itself 🤣. Strange.
